services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: optimi-web-frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:80"
    networks:
      - optimi-web-network

networks:
  optimi-web-network:
    driver: bridge
